# Generated by Django 4.1.1 on 2022-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='date_employed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
