# Generated by Django 4.1.1 on 2022-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_postion_employment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
