# Generated by Django 4.1.1 on 2022-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_member_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='monthly_rate',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_title',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=255),
        ),
    ]
