# Generated by Django 4.1.1 on 2022-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_monthly_rate_subscription_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
