# Generated by Django 4.1.1 on 2022-10-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_savingcontribution_saving_alter_saving_amount_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcontribution',
            name='saving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.saving'),
        ),
    ]
