# Generated by Django 4.1.1 on 2022-10-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_cancellation_reason'),
        ('finance', '0002_alter_contribution_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contribution',
            new_name='SavingContribution',
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
            ],
        ),
    ]
