# Generated by Django 4.1.1 on 2022-10-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_merigoroundcontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcontribution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='savingcontribution',
            name='updated',
        ),
    ]
