# Generated by Django 4.1.1 on 2022-10-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loantype'),
        ('users', '0007_subscription_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membership'),
        ),
    ]
