# Generated by Django 4.1.1 on 2022-10-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_savingcontribution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
