# Generated by Django 4.1.1 on 2022-10-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_saving_amount_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcontribution',
            name='saving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.saving'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
