# Generated by Django 4.1.1 on 2022-10-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_updated_subscription_mpesadetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='membership',
        ),
    ]
