# Generated by Django 4.1.1 on 2022-10-02 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_cancellation_reason'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.member'),
        ),
    ]
