# Generated by Django 4.1.1 on 2022-10-19 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanpayment_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanguarantor',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan'),
        ),
    ]
