# Generated by Django 4.1.1 on 2022-10-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanguarantor_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanguarantor',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
    ]
