# Generated by Django 4.1.2 on 2022-11-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_alter_loanguarantor_loan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("declined", "Declined"),
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=40,
            ),
        ),
    ]
