# Generated by Django 4.1.1 on 2022-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loan_amount_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_awarded',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
