# Generated by Django 4.1.1 on 2022-10-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_alter_loan_amount_awarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_awared',
            new_name='date_awarded',
        ),
    ]
