# Generated by Django 4.1.1 on 2022-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loan_amount_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_awarded',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
