# Generated by Django 4.1.1 on 2022-10-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_subscription_cancellation_reason'),
        ('loans', '0002_loanpayment_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member'),
        ),
    ]
