# Generated by Django 4.1.1 on 2022-10-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_rename_date_awared_loan_date_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loanapplication'),
        ),
    ]
