# Generated by Django 4.1.1 on 2022-10-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loantype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loantype',
            old_name='number_of_guarators',
            new_name='number_of_guarantors',
        ),
    ]
